---
title: "Individual Variable Exploration"
author: "Grace Kumaishi"
date: "4/3/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(ggplot2)
library(stringr)
library(dplyr)
```

```{r}
# Read in data:
CVA_scores <- read_csv(here("data", "CVA_scores_tidy.csv"))
```

#### CLIMATE VARIABLES ONLY (MOD - VERY HIGH)
```{r}
sensitivity_mod_above <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(mod_and_above = rowSums(select(., -c(1:2)) >= 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = sensitivity_mod_above, aes(x = mod_and_above, y = reorder(variable, mod_and_above))) +
  geom_col(fill = "#301934") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Frequency of Individual Climate Sensitivity Variables \n (Moderate, High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

#### CLIMATE VARIABLES ONLY (HIGH - VERY HIGH)
```{r}
sensitivity_high_above <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = sensitivity_high_above, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Count of Individual Climate Sensitivity Variables \n Scored 'High' and 'Very High' Across Habitats") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5)) 
```

#### BY HABITAT
```{r}
sensitivity_by_habitat <- sensitivity_high_above %>%
  select(!high_and_above) %>% 
  pivot_longer(cols = 3:26, names_to = "species", values_to = "score") %>%
  mutate(habitat = case_when(
    species %in% c("cowcod", "lingcod", "cnidarian", "sponge") ~ "Deep Sea",
    species %in% c("ca_sheephead", "kelp_bass", "red_urchin", "spiny_lobster", "giant_kelp") ~ "Kelp Forest",
    species %in% c("anchovy", "sardine", "white_shark", "swordfish", "brown_pelican", "scripps_murrelet") ~ "Pelagic",
    species %in% c("golden_rockweed", "black_abalone", "ochre_sea_star", "ca_mussel") ~ "Rocky Shore",
    species %in% c("eelgrass", "ca_halibut", "warty_sea_cuc", "rock_crab_spp") ~ "Sandy Seafloor",
    species %in% c("pac_sand_crab") ~ "Sandy Beach",
    )) %>%
  filter(score > 3) %>% 
  group_by(variable) %>% 
  mutate(count_score = n())
```

```{r}
# Specify habitat order
sensitivity_by_habitat$habitat <- factor(sensitivity_by_habitat$habitat, levels = c("Deep Sea", "Kelp Forest", "Pelagic", "Rocky Shore", "Sandy Seafloor", "Sandy Beach"))

ggplot(data = sensitivity_by_habitat, aes(y = reorder(variable, count_score))) +
  geom_bar(aes(fill = habitat), position = position_stack(reverse = TRUE)) +
  scale_fill_manual(breaks = c("Deep Sea", "Kelp Forest", "Pelagic", "Rocky Shore", "Sandy Seafloor", "Sandy Beach"), 
                    values = c("#2f4668", "#00a871", "#0d7ea2", "#936f38", "#86b98e", "#ffe396")) +
  labs(y = element_blank()) +
  theme_minimal() 
```


## SANDY BEACH
```{r}
sandy_beach <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  filter(habitat == "sandy_beach") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = sandy_beach, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Sandy Beach: Frequency of Individual Climate Sensitivity Variables \n (High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

## KELP FOREST
```{r}
kelp_forest <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  filter(habitat == "kelp_forest") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = kelp_forest, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Kelp Forest: Frequency of Individual Climate Sensitivity Variables \n (High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

## PELAGIC
```{r}
pelagic <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  filter(habitat %in% c("pelagic", "pelagic_seabirds")) %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = pelagic, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Pelagic: Frequency of Individual Climate Sensitivity Variables \n (High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

## DEEP SEAFLOOR
```{r}
deep_seafloor <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  filter(habitat == "deep_seafloor") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = deep_seafloor, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Deep Seafloor: Frequency of Individual Climate Sensitivity Variables \n (High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

## ROCKY SHORE
```{r}
rocky_shore <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  filter(habitat == "rocky_shore") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = rocky_shore, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Rocky Shore: Frequency of Individual Climate Sensitivity Variables \n (High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

## SANDY SEAFLOOR
```{r}
sandy_seafloor <- CVA_scores %>% 
  filter(component == "sensitivity") %>% 
  filter(habitat == "sandy_seafloor") %>% 
  select(1:18) %>% 
  select(!habitat) %>% 
  pivot_longer(3:17,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(high_and_above = rowSums(select(., -c(1:2)) > 3)) %>% 
  mutate(variable = case_when(
    variable == "air_temp" ~ "Air temperature",
    variable == "sst" ~ "Sea surface temperature",
    variable == "sub_surf_temp" ~ "Subsurface temperature",
    variable == "water_temp" ~ "Water temperature",
    variable == "salinity" ~ "Salinity",
    variable == "do" ~ "Dissolved oxygen",
    variable == "oa" ~ "Ocean acidification",
    variable == "slr" ~ "Sea level rise",
    variable == "wave_action" ~ "Wave action",
    variable == "upwelling" ~ "Upwelling",
    variable == "hab" ~ "Harmful algal blooms",
    variable == "precip_o" ~ "Precipitation events",
    variable == "dessication_o" ~ "Desiccation",
    variable == "turbidity_o" ~ "Turbidity",
    variable == "currents_o" ~ "Currents"
  ))
```

```{r}
ggplot(data = sandy_seafloor, aes(x = high_and_above, y = reorder(variable, high_and_above))) +
  geom_col(fill = "#00008B") +
  labs(y = "Climate Variable",
       x = "Count",
       title = "Sandy Seafloor: Frequency of Individual Climate Sensitivity Variables \n (High and Very High)") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .3)) 
```

