---
title: "Maritime Heritage Resources"
author: "Grace Kumaishi"
date: "4/16/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(ggplot2)
library(scales)
```

### Read in MHR data ###
```{r}
mhr <- read_csv(here("data", "mhr.csv"))
```

### Climate sensitivity ###
```{r}
climate_sensitivity <- mhr %>% 
  filter(component == "climate_sensitivity") %>% 
  replace(is.na(.), 0) %>% 
  mutate(factor = case_when(
   factor == "air_temp" ~ "Air temperature",
   factor == "water_temp" ~ "Water temperature",
   factor == "precipitation" ~ "Precipitation",
   factor == "salinity" ~ "Salinity",
   factor == "do" ~ "Dissolved oxygen",
   factor == "ph" ~ "Ocean acidification",
   factor == "inc_water_depth" ~ "Increased water depth",
   factor == "wave_tide" ~ "Wave/tidal action",
   factor == "flow_velocity" ~ "Water flow velocity",
   factor == "site_erosion" ~ "Site erosion",
   factor == "sedimentation" ~ "Sedimentation",
   factor == "surge_inundation" ~ "Storm surge/inundation"
  )) %>% 
  mutate(mhr_category = case_when(
    mhr_category == "nearshore" ~ "Nearshore",
    mhr_category == "offshore" ~ "Offshore"
  ))
```

```{r}
ggplot(data = climate_sensitivity, 
       aes(color = mhr_category, size = mhr_category, x = score, y = reorder(factor, score))) +
  scale_color_manual(breaks = c("Offshore", "Nearshore"), values = c("#274863" ,"#aacdec")) +
  scale_size_manual(breaks = c("Offshore", "Nearshore"), values = c(2, 5)) +
  geom_point(stat = "identity") +
  theme_minimal() +
  labs(y = "Climate Variable",
       x = "Sensitivity Score",
       #title = "Comparison of Climate Sensitivity Scores Between \n Nearshore and Offshore Maritime Heritage Resources",
       color = "MHR Category",
       size = "MHR Category"
  ) +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5),
                   labels = c("N/A", "Very Low", "Low", "Moderate", "High", "Very High")) +
  theme(plot.title = element_text(hjust = .5),
        panel.grid.minor = element_blank())
```

### Non-climate influence ###
```{r}
non_climate_impact <- mhr %>% 
  filter(component == "non_climate") %>% 
  replace(is.na(.), 0) %>% 
  mutate(factor = case_when(
    factor == "artifact_movt" ~ "Artifact movement",
    factor == "bio_chem_degredation" ~ "Biochemical degredation",
    factor == "fishing_trawling" ~ "Fishing and trawling",
    factor == "neglect" ~ "Neglect under NHPA",
    factor == "research_activities" ~ "Research activities",
    factor == "visitation" ~ "Visitation",
    factor == "vegetation" ~ "Marine vegetation growth"
  )) %>% 
  mutate(mhr_category = case_when(
    mhr_category == "nearshore" ~ "Nearshore",
    mhr_category == "offshore" ~ "Offshore"
  ))
```

```{r}
ggplot(data = non_climate_impact, 
       aes(color = mhr_category, size = mhr_category, x = score, y = reorder(factor, score))) +
  scale_color_manual(breaks = c("Offshore", "Nearshore"), values = c("#274863" ,"#aacdec")) +
  scale_size_manual(breaks = c("Offshore", "Nearshore"), values = c(2, 5)) +
  geom_point(position = "dodge", stat = "identity") +
  theme_minimal() +
  labs(y = "Non-Climate Variable",
       x = "Impact on Climate Sensitivity",
       #title = "Comparison of Non-Climate Impacts Between \n Nearshore and Offshore Maritime Heritage Resources",
       color = "MHR Category",
       size = "MHR Category"
  ) +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5),
                   labels = c("N/A", "Very Low", "Low", "Moderate", "High", "Very High")) +
  theme(plot.title = element_text(hjust = .5),
        panel.grid.minor = element_blank())
```






