---
title: "Non-climate variables"
author: "Grace Kumaishi"
date: "4/11/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
library(ggplot2)
library(stringr)
```

```{r}
# Read in data:
non_climate_raw <- read_csv(here("data", "non_climate_variables.csv"))
```

##### NOT FILTERED BY VALUE/SCORE ##### 

```{r}
### COUNT occurrence of non-climate variables
non_climate_tidy <- non_climate_raw %>% 
  select(!habitat) %>% 
  pivot_longer(2:25,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, 
              values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(occ_count = rowSums(select(., c(-1)) >= 1)) %>% 
  mutate(variable = case_when(
    variable == "fishing" ~ "Fishing",
    variable == "contaminants_seeps" ~ "Contaminants & seeps",
    variable == "disease" ~ "Disease",
    variable == "offshore_energy" ~ "Offshore energy",
    variable == "anthro_oil_spills" ~ "Anthropogenic oil spills",
    variable == "trap_fishing_bottom_contact" ~ "Trap fishing (bottom contact)",
    variable == "marine_debris" ~ "Marine debris",
    variable == "invasive_spp" ~ "Invasive species",
    variable == "harvest" ~ "Harvest",
    variable == "trampling" ~ "Trampling",
    variable == "submarine_cables" ~ "Submarine cables",
    variable == "recreation" ~ "Recreation",
    variable == "microplastics" ~ "Microplastics",
    variable == "beach_use" ~ "Beach use",
    variable == "aquaculture" ~ "Aquaculture",
    variable == "urchin_impacts" ~ "Urchin impacts",
    variable == "sedimentation" ~ "Sedimentation",
    variable == "predator_decline" ~ "Predator decline",
    variable == "predation" ~ "Predation",
    variable == "nursury_habitat_impacts" ~ "Nursury habitat degredation",
    variable == "island_ecosys_mgmt" ~ "Island ecosystem management",
    variable == "food_availability" ~ "Food availability",
    variable == "construction" ~ "Construction",
    variable == "anchoring" ~ "Anchoring"
  ))
```

```{r}
### PLOT
ggplot(data = non_climate_tidy, aes(x = occ_count, y = reorder(variable, occ_count))) +
  geom_col(fill = "#301934") +
  labs(y = "Non-climate variable",
       x = "Count",
       title = "Non-Climate Variables that Impact \n Species' Sensitivity to Climate Change") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5)) 
```

##### FILTERED HIGH OR VERY HIGH ##### 

```{r}
### COUNT occurrence of non-climate variables HIGH OR VERY HIGH
non_climate_high <- non_climate_raw %>% 
  select(!habitat) %>% 
  pivot_longer(2:25,
               names_to = "variable",
               values_to = "count") %>% 
  pivot_wider(names_from = species, 
              values_from = count) %>% 
  replace(is.na(.), 0) %>% 
  mutate(occ_count = rowSums(select(., c(-1)) >= 4)) %>% 
  mutate(variable = case_when(
    variable == "fishing" ~ "Fishing",
    variable == "contaminants_seeps" ~ "Contaminants & seeps",
    variable == "disease" ~ "Disease",
    variable == "offshore_energy" ~ "Offshore energy",
    variable == "anthro_oil_spills" ~ "Anthropogenic oil spills",
    variable == "trap_fishing_bottom_contact" ~ "Trap fishing (bottom contact)",
    variable == "marine_debris" ~ "Marine debris",
    variable == "invasive_spp" ~ "Invasive species",
    variable == "harvest" ~ "Harvest",
    variable == "trampling" ~ "Trampling",
    variable == "submarine_cables" ~ "Submarine cables",
    variable == "recreation" ~ "Recreation",
    variable == "microplastics" ~ "Microplastics",
    variable == "beach_use" ~ "Beach use",
    variable == "aquaculture" ~ "Aquaculture",
    variable == "urchin_impacts" ~ "Urchin impacts",
    variable == "sedimentation" ~ "Sedimentation",
    variable == "predator_decline" ~ "Predator decline",
    variable == "predation" ~ "Predation",
    variable == "nursury_habitat_impacts" ~ "Nursury habitat degredation",
    variable == "island_ecosys_mgmt" ~ "Island ecosystem management",
    variable == "food_availability" ~ "Food availability",
    variable == "construction" ~ "Construction",
    variable == "anchoring" ~ "Anchoring"
  ))
```

```{r}
### PLOT
ggplot(data = non_climate_high, aes(x = occ_count, y = reorder(variable, occ_count))) +
  geom_col(fill = "#00008B") +
  theme_minimal() +
  labs(y = "Non-climate variable",
       x = "Count",
       title = "Non-Climate Variables that 'Highly' or 'Very Highly' Impact \n Species' Sensitivity to Climate Change") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = .5)) 
```

#### BY HABITAT
```{r}
non_climate_by_habitat <- non_climate_high %>% 
  select(!occ_count) %>% 
  pivot_longer(cols = 2:25, names_to = "species", values_to = "score") %>%
  mutate(habitat = case_when(
    species %in% c("cowcod", "lingcod", "cnidarian", "sponge") ~ "Deep Sea",
    species %in% c("ca_sheephead", "kelp_bass", "red_urchin", "spiny_lobster", "giant_kelp") ~ "Kelp Forest",
    species %in% c("anchovy", "sardine", "white_shark", "swordfish", "brown_pelican", "scripps_murrelet") ~ "Pelagic",
    species %in% c("golden_rockweed", "black_abalone", "ochre_sea_star", "ca_mussel") ~ "Rocky Shore",
    species %in% c("eelgrass", "ca_halibut", "warty_sea_cuc", "rock_crab_spp") ~ "Sandy Seafloor",
    species %in% c("pac_sand_crab") ~ "Sandy Beach",
    )) %>%
  filter(score > 3) %>% 
  group_by(variable) %>% 
  mutate(count_score = n())
```

```{r}
# Specify habitat order
non_climate_by_habitat$habitat <- factor(non_climate_by_habitat$habitat, levels = c("Deep Sea", "Kelp Forest", "Pelagic", "Rocky Shore", "Sandy Seafloor", "Sandy Beach"))

ggplot(data = non_climate_by_habitat, aes(y = reorder(variable, count_score))) +
  geom_bar(width = 0.7, aes(fill = habitat), position = position_stack(reverse = TRUE)) +
  scale_fill_manual(breaks = c("Deep Sea", "Pelagic", "Kelp Forest", "Rocky Shore", "Sandy Seafloor", "Sandy Beach"), 
                    values = c("#2f4668", "#2378c3", "#7e9c1d", "#7a591a", "#fa9441", "#fee685")) +
  labs(y = "Climate Variable",
       x = "Count",
       #title = "Count of Individual Climate Sensitivity Variables \n Scored 'High' and 'Very High' Across Species",
       fill = "Habitat") +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4, 5, 6, 7, 8)) +
  theme(plot.title = element_text(hjust = .5)) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())
```




